### ISSUE TITLE
Hide default "Posts" if not needed

### ISSUE THREAD

**Issue by mandiwise** [redacademy/granville-spring-2017#3] opened 2017-06-22 17:10 UTC
If the client doesn't require a blog, you can hide the Posts-related UI elements with this plugin:

https://gist.github.com/mandiwise/2ea571ae0773b340af5a

**Comment by wtLau** [comment] 2017-06-22 17:40
The client needs a blog post. Just confirmed a new layout  with designers, working on it now.

**Comment by rcass** [comment] 2017-06-22 18:13
Alright sounds good. Just close this issue once you have finished building that blog. Since blog functionality is built into WordPress, this feature should not take long to implement.

**Closed as completed** 2017-06-26 05:43 UTC
